# App-specific tweaks
source = ~/.local/share/dotfiles/default/hypr/conf/apps/browser.conf
source = ~/.local/share/dotfiles/default/hypr/conf/apps/davinci-resolve.conf
source = ~/.local/share/dotfiles/default/hypr/conf/apps/hyprshot.conf
source = ~/.local/share/dotfiles/default/hypr/conf/apps/localsend.conf
source = ~/.local/share/dotfiles/default/hypr/conf/apps/pip.conf
source = ~/.local/share/dotfiles/default/hypr/conf/apps/qemu.conf
source = ~/.local/share/dotfiles/default/hypr/conf/apps/retroarch.conf
source = ~/.local/share/dotfiles/default/hypr/conf/apps/steam.conf
source = ~/.local/share/dotfiles/default/hypr/conf/apps/sysapp.conf
source = ~/.local/share/dotfiles/default/hypr/conf/apps/terminals.conf
source = ~/.local/share/dotfiles/default/hypr/conf/apps/webcam-overlay.conf
