source = ~/.config/dotfiles/hypr/conf/bindings/media.conf
source = ~/.config/dotfiles/hypr/conf/bindings/tiling.conf
source = ~/.config/dotfiles/hypr/conf/bindings/utilities.conf
source = ~/.config/dotfiles/hypr/conf/bindings/clipboard.conf
