source = ~/.local/share/dotfiles/default/hypr/conf/bindings/media.conf
source = ~/.local/share/dotfiles/default/hypr/conf/bindings/tiling.conf
source = ~/.local/share/dotfiles/default/hypr/conf/bindings/utilities.conf
source = ~/.local/share/dotfiles/default/hypr/conf/bindings/clipboard.conf
