# App-specific tweaks
source = ./apps/browser.conf
source = ./apps/davinci-resolve.conf
source = ./apps/hyprshot.conf
source = ./apps/localsend.conf
source = ./apps/pip.conf
source = ./apps/qemu.conf
source = ./apps/retroarch.conf
source = ./apps/steam.conf
source = ./apps/sysapp.conf
source = ./apps/terminals.conf
source = ./apps/webcam-overlay.conf
