[[ $- != *i* ]] && return

iatest=$(expr index "$-" i)

if [ -f /usr/bin/fastfetch ]; then
  fastfetch
fi

for f in "$HOME/.local/share/dotfiles/default/bash"/*; do
  if [ ! -d "$f" ]; then
    filename=$(basename "$f")
    override="$HOME/.bashrc.d/$filename"
    [[ -f "$override" ]] && source "$override" || source "$f"
  fi
done

if [ -f /usr/share/bash-completion/bash_completion ]; then
  . /usr/share/bash-completion/bash_completion
elif [ -f /etc/bash_completion ]; then
  . /etc/bash_completion
fi
