# -------System-------
source = ../system/hypr/system.conf

# -------User-------
source = ./conf/monitors.conf
source = ./conf/input.conf
source = ./conf/looknfeel.conf
source = ./conf/autostart.conf
source = ./conf/keybindings.conf
