# -------Default-------
source = ~/.local/share/dotfiles/default/hypr/hyprland.conf

# -------Theme-------
source = ~/.local/share/dotfiles/themes/current/hyprland.conf

# -------User-------
source = ~/.config/hypr/conf/monitors.conf
source = ~/.config/hypr/conf/input.conf
source = ~/.config/hypr/conf/looknfeel.conf
source = ~/.config/hypr/conf/autostart.conf
source = ~/.config/hypr/conf/keybindings.conf
